---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: open-webui
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: OPENAI_API_KEY
            - name: ENABLE_OLLAMA_API
              value: "false"
            - name: ENABLE_OPENAI_API
              value: "true"
            - name: GLOBAL_LOG_LEVEL
              value: DEBUG
            - name: OPENAI_API_BASE_URL
              value: http://litellm.{{ .Release.Namespace }}.svc.cluster.local:4000/v1
            - name: WEBUI_SECRET_KEY
              value: dummy
            - name: DEFAULT_MODELS
              value: "auto"
            - name: DEFAULT_MAX_TOKENS
              value: "100"
            - name: DEFAULT_TEMPERATURE
              value: "0.7"  
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: open-webui
              mountPath: /app/backend/data
          image: 'ghcr.io/open-webui/open-webui:main'
      serviceAccountName: open-webui
      volumes:
        - name: open-webui
          persistentVolumeClaim:
            claimName: open-webui
